# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 6.32856386773
    has_acceleration_limits: true
    max_acceleration: 5.65050345333
  joint2:
    has_velocity_limits: true
    max_velocity: 5.30231026755
    has_acceleration_limits: true
    max_acceleration: 1.80350689372
  joint3:
    has_velocity_limits: true
    max_velocity: 7.01273293451
    has_acceleration_limits: true
    max_acceleration: 3.57792496658
  joint4:
    has_velocity_limits: true
    max_velocity: 9.40732466824
    has_acceleration_limits: true
    max_acceleration: 23.99827721492
  joint5:
    has_velocity_limits: true
    max_velocity: 9.40732466824
    has_acceleration_limits: true
    max_acceleration: 23.99827721492
  joint6:
    has_velocity_limits: true
    max_velocity: 17.10422666954
    has_acceleration_limits: true
    max_acceleration: 13.08996938995
