# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_position_limits: true
    min_position: -3.14159265359
    max_position: 3.14159265359
    has_velocity_limits: true
    max_velocity: 3.316125578789
    has_acceleration_limits: true
    max_acceleration: 4.1041158153
  joint2:
    has_position_limits: true
    min_position: -1.83259571459
    max_position: 2.70526034059
    has_velocity_limits: true
    max_velocity: 3.577924966588
    has_acceleration_limits: true
    max_acceleration: 2.5556606904
  joint3:
    has_position_limits: true
    min_position: -2.84488668075 
    max_position: 2.61799387799 
    has_velocity_limits: true
    max_velocity: 3.518583772021
    has_acceleration_limits: true
    max_acceleration: 2.6431668960
  joint4:
    has_position_limits: true
    min_position: -4.71238898039 
    max_position: 4.71238898039 
    has_velocity_limits: true
    max_velocity: 6.702064327658
    has_acceleration_limits: true
    max_acceleration: 16.311488336
  joint5:
    has_position_limits: true
    min_position: -2.53072741539
    max_position: 2.53072741539
    has_velocity_limits: true
    max_velocity: 6.283185307180
    has_acceleration_limits: true
    max_acceleration: 10.833078115
  joint6:
    has_position_limits: true
    min_position: -6.28318530718
    max_position: 6.28318530718
    has_velocity_limits: true
    max_velocity: 10.646508437165
    has_acceleration_limits: true
    max_acceleration: 10.316384144