# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_position_limits: true
    min_position: -3.14159265359
    max_position: 3.14159265359
    has_velocity_limits: true
    max_velocity: 3.67740873395
    has_acceleration_limits: true
    max_acceleration: 5.00327718905
  joint2:
    has_position_limits: true
    min_position: -1.74532925199
    max_position: 2.28638132011
    has_velocity_limits: true
    max_velocity: 3.67740873395
    has_acceleration_limits: true
    max_acceleration: 1.94092649575
  joint3:
    has_position_limits: true
    min_position: -2.80998009571
    max_position: 2.53072741539
    has_velocity_limits: true
    max_velocity: 4.61814120078
    has_acceleration_limits: true
    max_acceleration: 5.19748784601
  joint4:
    has_position_limits: true
    min_position: -4.71238898038
    max_position: 4.71238898038
    has_velocity_limits: true
    max_velocity: 7.18377520121
    has_acceleration_limits: true
    max_acceleration: 3.18712298190
  joint5:
    has_position_limits: true
    min_position: -2.53072741539
    max_position: 2.53072741539
    has_velocity_limits: true
    max_velocity: 7.18377520121
    has_acceleration_limits: true
    max_acceleration: 35.1710288660
  joint6:
    has_position_limits: true
    min_position: -6.28318530718
    max_position: 6.28318530718
    has_velocity_limits: true
    max_velocity: 13.34129680224
    has_acceleration_limits: true
    max_acceleration: 21.0391508013
