# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 2.98451302091
    has_acceleration_limits: true
    max_acceleration: 2.75578302946
  joint2:
    has_velocity_limits: true
    max_velocity: 2.98451302091
    has_acceleration_limits: true
    max_acceleration: 2.61799387799
  joint3:
    has_velocity_limits: true
    max_velocity: 2.652900463031
    has_acceleration_limits: true
    max_acceleration: 2.02945261859
  joint4:
    has_velocity_limits: true
    max_velocity: 3.067416160380
    has_acceleration_limits: true
    max_acceleration: 10.69158647744
  joint5:
    has_velocity_limits: true
    max_velocity: 2.735803602501
    has_acceleration_limits: true
    max_acceleration: 4.79965544298
  joint6:
    has_velocity_limits: true
    max_velocity: 4.642575810305
    has_acceleration_limits: true
    max_acceleration: 15.76426421156